In [2]:
import torch
x = torch.arange(20).view(4,5)
x

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [12]:
x.view(2,10).split(5,dim=1)

(tensor([[ 0,  1,  2,  3,  4],
         [10, 11, 12, 13, 14]]),
 tensor([[ 5,  6,  7,  8,  9],
         [15, 16, 17, 18, 19]]))

In [9]:
x.view(2,10).transpose(1,2).reshape(5,4)

tensor([[ 0,  5,  1,  6],
        [ 2,  7,  3,  8],
        [ 4,  9, 10, 15],
        [11, 16, 12, 17],
        [13, 18, 14, 19]])

In [ ]:
import 